import Head from 'next/head';
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';
import Job from './Job';
import { useFetch } from '../hooks/useFetch';
import paginate from '../utils/paginate';
export default function Home() {
  const { jobs, debouncedSearch, setSearch, loading } = useFetch();
  const [page, setPage] = useState(0);
  const [items, setItems] = useState([]);
  const jobsFilter = jobs.data?.filter((value) => {
    if (debouncedSearch === ``) {
      return value;
    } else if (debouncedSearch === null) {
      return value;
    } else if (
      value.title?.toLowerCase().startsWith(debouncedSearch?.toLowerCase())
    ) {
      return value;
    }
  });
  useEffect(() => {
    if (loading) return;
    setItems(jobs);
  }, [loading]);
  const jobsFilterCalc = Math.ceil(jobsFilter?.length / 10);
  console.log(jobsFilterCalc);
  return (
    <div className={styles.container}>
      <Head>
        <title>Zerezes Code Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>oi</h1>
        <input
          type="search"
          placeholder="Pesquisar"
          onChange={(e) => setSearch(e.target.value)}
        />
        <section className="Job-listing">
          <div className="container">
            {paginate(jobsFilter, page)?.map((job) => {
              return <Job key={job.slug} {...job} />;
            })}
          </div>
          {/* {!loading && (
            <div className="btn-container">
              {jobsFilterCalc?.map((item, index) => {
                return (
                  <button key={index} className="page-btn">
                    botao
                  </button>
                );
              })}
            </div>
          )} */}
        </section>
      </main>
    </div>
  );
}
